[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
force = false
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [
    { access = 'read-write', path = 'deployments/' },
    { access = 'read', path = 'deploy-config/' },
    { access = 'read', path = 'broadcast/' },
    { access = 'read', path = 'script/' },
]

verbosity = 2
ffi = false
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[profile.intense]
fuzz = { runs = 10000 }

# Network configuration
[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
xlayer_test = "${XLAYER_TEST_RPC}"

[etherscan]
bsc_testnet = { key = "5FCIE4WK4IU1DNCAGGBXNZJPK49YMIS5FT", url = "https://api-testnet.bscscan.com/api", chain = 97 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
